### PR TITLE
Dune 2.0.0 plan

### PR DESCRIPTION
**Pull request by diml**
This post announces our plans for Dune 2.0.0. I'm away from tomorrow until the end of next week, so I'll finish and post it when I come back.

### CODE REVIEW

**Comment by emillon** [comment]
Sidenote, IIRC you can put the post without date under `_drafts` and it's possible to rename it with the current date as a command.

**Comment by diml** [comment]
Ah, that's nice. Do you know which command it is?

**Comment by diml** [comment]
Ok, this is ready for review!

**Comment by diml** [comment]
Alright, I did another pass. This is ready for posting!

**Pull request merged**
